### ISSUE TITLE
在复现您项目过程中  遇到如下错误

### ISSUE THREAD

**Issue by neverstoplearn** [TWSFar/DSSD#2]
[mode: train, Epoch: [0], lr: 0.0009821, average_loc_loss:  2.61, average_conf_loss:  3.35, time:   3.9m]
:   0%|                                                | 0/181 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 217, in <module>
    main()
  File "train.py", line 194, in main
    map, mf1 = evaluator.validation(trainer.model, epoch)
  File "/mnt/sda7/DSSD/eval.py", line 79, in validation
    output = self.model(images, mode='val')
  File "/home/wuwenfu/.conda/envs/pytorch10/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sda7/DSSD/model/DSSD.py", line 63, in forward
    self.priors
  File "/home/wuwenfu/.conda/envs/pytorch10/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sda7/DSSD/model/functions/detection.py", line 45, in forward
    keep = nms_cpu(boxes, scores, self.nms_thresh, self.top_k)
  File "/mnt/sda7/DSSD/model/nms/nms_cpu.py", line 28, in nms_cpu
    inds = torch.where(iou <= thresh)[0]
TypeError: where() missing 2 required positional argument: "input", "other"

**Comment by TWSFar** [comment]
换成pytorch1.1.0试试


| |
段成真
|
|
twsfcz@163.com
|
签名由网易邮箱大师定制
在2019年9月16日 11:36，neverstoplearn<notifications@github.com> 写道：

[mode: train, Epoch: [0], lr: 0.0009821, average_loc_loss: 2.61, average_conf_loss: 3.35, time: 3.9m]
: 0%| | 0/181 [00:00<?, ?it/s]Traceback (most recent call last):
File "train.py", line 217, in
main()
File "train.py", line 194, in main
map, mf1 = evaluator.validation(trainer.model, epoch)
File "/mnt/sda7/DSSD/eval.py", line 79, in validation
output = self.model(images, mode='val')
File "/home/wuwenfu/.conda/envs/pytorch10/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/mnt/sda7/DSSD/model/DSSD.py", line 63, in forward
self.priors
File "/home/wuwenfu/.conda/envs/pytorch10/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/mnt/sda7/DSSD/model/functions/detection.py", line 45, in forward
keep = nms_cpu(boxes, scores, self.nms_thresh, self.top_k)
File "/mnt/sda7/DSSD/model/nms/nms_cpu.py", line 28, in nms_cpu
inds = torch.where(iou <= thresh)[0]
TypeError: where() missing 2 required positional argument: "input", "other"

**Comment by zhengxinvip** [comment]
尝试了pytorch1.0  1.1 1.2均出现错误 我再好好看看代码 谢谢

**Comment by TWSFar** [comment]
我自己也遇到这个问题了， 我发现pytorch1.2就没事， 但是1.1就报错, 可以修改成如下形式
`# inds = torch.where(iou <= thresh)[0]
 # order = order[inds + 1]
 order = order[1:][iou <= thresh]`

**Comment by zhengxinvip** [comment]
谢谢 稍后我再试试
